#!/bin/bash

set -o errexit

main() {
  local domain=$1

  if [[ -z "$domain" ]]; then
    echo "ERROR: At least one domain must be specified.

  Usage:  certgen <domain>

Aborting."
    exit 1
  fi

  set -o nounset

  generate_cert "$domain"
}

# Generates an OpenSSL configuration file that
# specifies some extra properties that we're not
# able to when running the command directly.
#
# note.: the main property we're configuring here is
# the alternate name. See more at the following addr:
# http://wiki.cacert.org/FAQ/subjectAltName
generate_openssl_conf_for_domain() {
  local domain=$1
  local conf_file=$(mktemp)

  echo "
[ req ]
req_extensions          = v3_req
distinguished_name      = req_distinguished_name
attributes		          = req_attributes

[ v3_req ]
subjectAltName          = @alt_names

[ alt_names ]
DNS.1                   = $domain

[ req_distinguished_name ]
countryName			        = Country Name (2 letter code)
countryName_min		      = 2
countryName_max		      = 2
stateOrProvinceName     = State or Province Name (full name)
localityName			      = Locality Name (eg, city)
0.organizationName    	= Organization Name (eg, company)
organizationalUnitName	= Organizational Unit Name (eg, section)
commonName		          = Common Name (eg, fully qualified host name)
commonName_max         	= 64
emailAddress	         	= Email Address
emailAddress_max		    = 64

[ req_attributes ]
challengePassword		    = A challenge password
challengePassword_min		= 4
challengePassword_max		= 20
" >$conf_file

  echo "$conf_file"
}

generate_cert() {
  local dir_name="."
  local domain=$1
  local key_name="key_$domain.pem"
  local cert_name="cert_$domain.pem"
  local haproxy_cert="haproxy_$domain.pem"
  local openssl_conf=$(generate_openssl_conf_for_domain $domain)

  ALTNAME="DNS:$domain" \
    openssl req \
    -x509 \
    -sha256 \
    -newkey rsa:4096 \
    -keyout "$key_name" \
    -out "$cert_name" \
    -days 730 \
    -nodes \
    -config "$openssl_conf" \
    -extensions v3_req \
    -subj "/C=BR/ST=SaoPaulo/L=SaoPaulo/O=TestOrg/OU=TestUnit/CN=$domain"

  cat $key_name $cert_name >$haproxy_cert

  chmod 644 $haproxy_cert
}

main "$@"
